name: CI

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8 coverage

      - name: Run linter
        run: |
          flake8 .

      - name: Run tests and Check Coverage (Per Game)
        run: |
          echo "Reporte de Cobertura: Blackjack"
          coverage run --source=blackjack -m unittest discover -s blackjack -t blackjack
          coverage report -m --fail-under=85

          # Copien esto para nuevos juegos EJEMPLO
          # echo "=== Reporte de Cobertura: Poker ==="
          # coverage run --source=poker -m unittest discover -s poker -t poker
          # coverage report -m --fail-under=85
